name: 🚀 Deploy website on push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ionos
    steps:
    - uses: actions/checkout@master
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: access976482937.webspace-data.io
        port: 22
        username: u113589676 
        password: ${{ secrets.FTP_PASSWORD }}
